authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/employer/', authapp.register_employer, name='register_employer'),
    path('register/jobseeker/', authapp.register_jobseeker, name='register_jobseeker'),
    path('edit/', authapp.edit, name='edit'),
    path('jobseeker/<int:pk>/edit/', authapp.JobseekerUpdateView.as_view(), name='edit_jobseeker'),
    path('edit/password/', authapp.UpdatePasswordView.as_view(), name='edit_password'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    re_path(r'^seeker_verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.seeker_verify, name='seeker_verify'),
    path('email_verify/', authapp.email_verify, name='email_verify'),
    path('edit/employer_password/', authapp.employer_change_password,
         name='employer_change_password')
]

employerapp/urls.py
from django.urls import path

from employerapp import views

app_name = 'employerapp'

urlpatterns = [
    path('<int:emp_id>/', views.employer_cabinet, name='main_cabinet'),
    path('<int:emp_id>/drafts/', views.vacancy_draft, name='drafts'),
    path('<int:emp_id>/published/', views.vacancy_published, name='published'),
    path('<int:emp_id>/messages/', views.messages, name='messages'),
    path('<int:emp_id>/hide/', views.vacancy_hide, name='hide'),
    path('<int:emp_id>/responses/', views.responses, name='responses'),
    path('<int:emp_id>/my_offers/', views.my_offers, name="my_offers"),
    path('<int:emp_id>/vacancy_create/', views.vacancy_create, name='vacancy_create'),
    path('<int:emp_id>/vacancy_draft_edit/<int:pk>/', views.vacancy_edit_draft,
         name='vacancy_edit_draft'),
    path('<int:emp_id>/vacancy_edit/<int:pk>/', views.vacancy_edit, name='vacancy_edit'),
    path('<int:emp_id>/vacancy_delete/<int:pk>/', views.vacancy_delete, name='vacancy_delete'),
    path('<int:emp_id>/vacancy_view/<int:pk>/', views.vacancy_view, name='vacancy_view'),
    path('<int:emp_id>/send_offer/<int:pk>', views.send_offer, name='send_offer'),
    path('<int:emp_id>/favorites/', views.favorites, name='favorites'),
    path('<int:emp_id>/favorite/create/', views.add_favorite, name='create_favorite'),
    path('<int:emp_id>/favorite_<int:pk>/delete/', views.delete_favorite, name='delete_favorite'),
    path('<int:emp_id>/search_resume/', views.search_resume, name='search_resume')
]

jobseekerapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from jobseekerapp import views

app_name = 'jobseekerapp'

urlpatterns = [
    path('<int:jobseeker_id>/', views.JobseekerDetailView.as_view(), name='cabinet'),
    path('<int:jobseeker_id>/resume/', views.create_resume, name='resume'),
    path('<int:seeker_id>/messages', views.messages, name='messages'),
    path('<int:jobseeker_id>/resume/<int:pk>/', login_required(views.ResumeDetailView.as_view()), name='resume_detail'),
    path('resume/<int:pk>/external/', views.ResumeExternalDetailView.as_view(), name='resume_external_detail'),
    path('<int:jobseeker_id>/resume/<int:pk>/edit/', views.resume_update, name='resume_update'),
    path('<int:jobseeker_id>/resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(), name='resume_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/', views.ResumeExperienceCreateView.as_view(),
         name='resume_experience'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/edit/',
         views.ResumeExperienceUpdateView.as_view(), name='resume_experience_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/delete/',
         views.ResumeExperienceDeleteView.as_view(), name='resume_experience_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/',
         views.ResumeEducationCreateView.as_view(), name='resume_education'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/edit/',
         views.ResumeEducationUpdateView.as_view(), name='resume_education_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/delete/',
         views.ResumeEducationDeleteView.as_view(), name='resume_education_delete'),
    path('<int:jobseeker_id>/offer/<int:vacancy_id>/create/', views.JobseekerOfferCreateView.as_view(),
         name='offer_create'),
    # path('<int:jobseeker_id>/offer/', views.JobseekerOfferListView.as_view(), name='offer_list'),
    path('<int:jobseeker_id>/offer/', views.offer_list, name='offer_list'),
    path('<int:jobseeker_id>/favorite/', views.JobseekerFavoriteListView.as_view(), name='favorite_list'),
    path('<int:jobseeker_id>/favorite/<int:pk>/delete/', views.JobseekerFavoriteDeleteView.as_view(),
         name='favorite_delete'),
    path('<int:jobseeker_id>/favorite/create/', views.add_favorite, name='favorite_create'),
    path('<int:jobseeker_id>/search_vacancy/',
         views.SearchVacancyListView.as_view(), name='search_vacancy'),
]

recruitsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views
from recruitsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('<int:page>/', views.main, name='main'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('site_news/<int:page>/', views.news, name='news'),
    path('news/search_news/', views.search_news, name='search_news'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('employer/', include('employerapp.urls', namespace='employer')),
    path('jobseeker/', include('jobseekerapp.urls', namespace='jobseeker')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.db import models


class IndustryType(models.Model):
    descx = models.CharField(verbose_name='Описание типа отрасли', max_length=64)

    class Meta:
        verbose_name_plural = 'Типы отраслей'

    def __str__(self):
        return self.descx


class Employer(models.Model):
    DRAFT = 'draft'
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    EMPLOYER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором'),
        (DRAFT, 'черновик')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    company_name = models.CharField(verbose_name='название компании', max_length=256, unique=True)
    tax_number = models.CharField(verbose_name='ИНН компании', max_length=16, blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11, blank=True)
    site = models.CharField(verbose_name='сайт компании', max_length=32, blank=True)
    industry_type = models.ForeignKey(IndustryType, on_delete=models.CASCADE, null=True, blank=True)
    short_description = models.TextField(verbose_name='краткое описание компании', blank=True)
    logo = models.ImageField(upload_to='company_logo', blank=True)
    city = models.CharField(verbose_name='город расположения компании', max_length=64, blank=True)
    is_active = models.BooleanField(default=True)
    status = models.CharField(verbose_name='статус компании на сайте',
                              choices=EMPLOYER_STATUS_CHOICES, default=NEED_MODER,
                              max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                        'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Работодатели'

    def __str__(self):
        return self.company_name


class Jobseeker(models.Model):
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    JOBSEEKER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором')
    )
    GENDER_CHOICES = (
        ('m', 'мужской'),
        ('f', 'женский'),
    )
    MARRIED_STATUS_CHOICES = (
        ('h', 'холост'),
        ('m', 'замужем/женат'),
        ('d', 'разведен/разведена'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    middle_name = models.CharField(verbose_name='отчество', max_length=32)
    gender = models.CharField(verbose_name='пол', max_length=16, choices=GENDER_CHOICES)
    birthday = models.DateField(verbose_name='дата рождения', null=True, blank=True)
    city = models.CharField(verbose_name='город', max_length=64)
    married_status = models.CharField(verbose_name='Статус в браке', max_length=1, choices=MARRIED_STATUS_CHOICES)
    photo = models.ImageField(upload_to='jobseeker_photo', blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11)
    about = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    status = models.CharField(verbose_name='статус соискателя на сайте',
                choices=JOBSEEKER_STATUS_CHOICES, default=NEED_MODER, max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                                            'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Соискатели'

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} (статус: {self.status})'

jobseekerapp/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

from authapp.models import Jobseeker


class Resume(models.Model):
    DRAFT = 'draft'
    OPENED = 'opened'
    NEED_MODER = 'need_moderation'
    MODER_REJECT = 'moderation_reject'
    RESUME_STATUS_CHOICES = (
        (DRAFT, 'черновик'),
        (OPENED, 'модерация пройдена успешно'),
        (NEED_MODER, 'требуется модерация'),
        (MODER_REJECT, 'модерация отклонена')
    )
    name = models.CharField(verbose_name='Желаемая должность', max_length=128)
    user = models.ForeignKey(Jobseeker, on_delete=models.CASCADE)
    salary_min = models.IntegerField(verbose_name='Минимальная зарплата', blank=True, null=True)
    salary_max = models.IntegerField(verbose_name='Максимальная зарплата', blank=True, null=True)
    currency = models.CharField(verbose_name='Валюта', max_length=3, blank=True, null=True)
    added_at = models.DateTimeField(verbose_name='Время добавления резюме', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Время обновления резюме', auto_now=True)
    key_skills = models.TextField(verbose_name='Ключевые навыки', blank=True, null=True)
    about = models.TextField(verbose_name='О себе', blank=True, null=True)
    status = models.CharField(verbose_name='Статус', choices=RESUME_STATUS_CHOICES,
                              max_length=32)
    failed_moderation = models.TextField(verbose_name='Сообщение в случае непрохождения '
                                                'модерации резюме', max_length=254, blank=True)
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    class Meta:
        verbose_name_plural = verbose_name = 'Резюме'

    def __str__(self):
        return f'{self.name} {self.user.user.first_name} {self.user.user.last_name}'

    def save(self, *args, **kwargs):
        if self.status == 'opened' or self.status == 'moderation_reject':
            self.updated_at = datetime.now()
        super(Resume, self).save(*args, **kwargs)

    def get_experience_items(self):
        return self.experienceitems.select_related().filter(is_active=True)

    def get_education_items(self):
        return self.educationitems.select_related().filter(is_active=True)

    @staticmethod
    def get_user_resumes(user_id):
        return Resume.objects.filter(is_active=True, user_id=user_id)

    def get_favorite_id(self, user_id):
        favorite = self.favoriteresumes.select_related().filter(employer=user_id)
        if favorite:
            return favorite.first().id
        return None


class ResumeEducation(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, verbose_name='Резюме', related_name='educationitems')
    HIGH = 'high'
    ONLINE = 'online'
    EDU_TYPE_CHOICES = (
        ('high', 'высшее'),
        ('online', 'онлайн-курсы'),
    )
    edu_type = models.CharField(verbose_name='Тип образования', max_length=32, choices=EDU_TYPE_CHOICES, blank=False, default=HIGH)
    MASTER = 'master'
    BACHELOR = 'bachelor'
    SPECIALIST = 'specialist'
    SERTIFICATE = 'sertificate'
    DEGREE_CHOICES = (
        (MASTER, 'магистр'),
        (BACHELOR, 'бакалавр'),
        (SPECIALIST, 'специлист'),
        (SERTIFICATE, 'сертификат'),
    )
    degree = models.CharField(verbose_name='Уровень', max_length=64, null=True, choices=DEGREE_CHOICES, blank=False, default=MASTER)
    institution_name = models.CharField(verbose_name='Название учреждения', max_length=64)
    from_date = models.DateField(verbose_name='Начало периода', blank=True, null=True)
    to_date = models.DateField(verbose_name='Конец периода(фактическая или планируемая)')
    course_name = models.CharField(verbose_name='Название курса/кафедры', max_length=256)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    class Meta:
        verbose_name = 'Место обучения для резюме'
        verbose_name_plural = 'Места обучения для резюме'

    def __str__(self):
        return f'{self.resume.name} {self.resume.user.user.first_name} {self.resume.user.user.last_name} ' \
               f'({self.get_edu_type_display()}, {self.get_degree_display()})'


class ResumeExperience(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='experienceitems')
    company_name = models.CharField(verbose_name='Название компании', max_length=128)
    job_title = models.CharField(verbose_name='Название вакансии', max_length=128)
    from_date = models.DateField(verbose_name='Начало работы')
    to_date = models.DateField(verbose_name='Конец работы', blank=True, null=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    class Meta:
        verbose_name = 'Место опыта для резюме'
        verbose_name_plural = 'Места опыта для резюме'

    def __str__(self):
        return f'{self.resume.name} {self.resume.user.user.first_name}' \
               f' {self.resume.user.user.last_name} {self.company_name} ' \
               f'{self.job_title}'


class Offer(models.Model):
    date = models.DateField(verbose_name='Дата направления отклика', auto_now_add=True)
    vacancy = models.ForeignKey('employerapp.Vacancy', on_delete=models.CASCADE, verbose_name='Вакансия')
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, verbose_name='Резюме')
    cover_letter = models.TextField(verbose_name='Сопроводительное письмо',
                                    blank=True, max_length=524, help_text='поле не обязательное')
    contact_phone = models.CharField(max_length=12, blank=True, help_text='поле не обязательное',
                                     verbose_name='Контактный телефон')

    OUTGOING = 'O'
    INCOMING = 'I'
    DIRECTION_CHOICES = (
        (OUTGOING, 'исходящий'),
        (INCOMING, 'входящий'),
    )
    direction = models.CharField(verbose_name='Направление отклика (входящее/исходящее)', max_length=1,
                                 choices=DIRECTION_CHOICES)

    NEW = 'new'
    READ = 'read'
    APPROVE = 'approve'
    FAIL = 'fail'
    OFFER_STATUSES = (
        (NEW, 'новое (не прочитано)'),
        (READ, 'прочитано'),
        (APPROVE, 'приглашение получено'),
        (FAIL, 'отклонено')
    )
    status = models.CharField(verbose_name='Статус предложения', choices=OFFER_STATUSES, default=NEW, max_length=16)

    class Meta:
        verbose_name_plural = 'Предложения по вакансиям от соискателей'

    def __str__(self):
        return f'{self.vacancy.employer.company_name}/{self.vacancy.vacancy_name} ({self.resume.name})'


class Favorite(models.Model):
    user = models.ForeignKey(Jobseeker, on_delete=models.CASCADE)
    vacancy = models.ForeignKey('employerapp.Vacancy', on_delete=models.CASCADE, related_name='favoritevacancies',
                                verbose_name='Вакансия')
    add_date = models.DateField(verbose_name='Дата добавления в избранное', auto_now_add=True)

    class Meta:
        unique_together = ('user', 'vacancy',)
        verbose_name_plural = 'Избранные вакансии'
        verbose_name = 'Избранная вакансия'

jobseekerapp/templates/jobseekerapp/favorite_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
   <div class="container">
       <h3 class="my-3 text-center">Уверены, что хотите удалить вакансию из избранного?</h3>
       <form action="{% url 'jobseeker:favorite_delete' user.pk object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger form-control last" type="submit" value="удалить">
       </form>
       <a class="btn btn-round form-control last" href="{% url 'jobseeker:favorite_list' user.pk %}">отмена</a>
   </div>
{% endblock %}

jobseekerapp/templates/jobseekerapp/jobseeker_cabinet.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<div class="container my-5">
    <div class="row">
        {% if object.status == 'moderation_ok' %}
        <div class="col-4 col-sm-2">
            <img class="img-fluid rounded shadow" src="/media/{{ jobseeker.photo }}" onerror ="this.src='{% static 'img/employers/example.jpg' %}';" alt="My image">
        </div>
        <div class="col-11 col-sm-10">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">{{ jobseeker.user.last_name }} {{ jobseeker.user.first_name }} {{ jobseeker.middle_name }}</th>
                </tr>
                <tr>
                    <th scope="col">Пол</th>
                    <th scope="col">{{ jobseeker.get_gender_display }}</th>
                </tr>
                <tr>
                    <th scope="col">День рождения</th>
                    <th scope="col">{{ jobseeker.birthday|date:"d.m.Y" }}</th>
                </tr>
                <tr>
                    <th scope="col">Город</th>
                    <th scope="col">{{ jobseeker.city }}</th>
                </tr>
                <tr>
                    <th scope="col">Номер телефона</th>
                    <th scope="col">{{ jobseeker.phone_number }}</th>
                </tr>
                <tr>
                    <th scope="col">Семейное положение</th>
                    <th scope="col">{{ jobseeker.get_married_status_display }}</th>
                </tr>
                <tr>
                    <th scope="col">О себе</th>
                    <th scope="col">{{ jobseeker.about }}</th>
                </tr>
                <tr>
                    <th scope="col">Статус</th>
                    <th scope="col">{{ jobseeker.get_status_display }}</th>
                </tr>
                </thead>
            </table>
            <a class="btn btn-primary mb-3" href="{% url 'auth:edit_jobseeker' jobseeker.pk %}">
                Редактировать
            </a>
            <a class="btn btn-success mb-3 ml-3" href="{% url 'auth:edit_password' %}">
                Сменить пароль
            </a>
            <h1 class="my-5">Мои резюме</h1>
            <table class="table employer_table">
                <tbody>
            {% if not resumes %}
                <tr>
                    <td scope="col"><p>У вас не заведено ни одно резюме</p></td>
                </tr>
            {% else %}
                {% for object in resumes %}
                    <tr>
                        <td scope="col">
                            <p>{{ object.name }}</p>
                            {% if object.salary_min and object.salary_max %}
                            <p>{{ object.salary_min }} - {{ object.salary_max }} {{ object.currency }}</p>
                            {% elif object.salary_min %}
                            <p>{{ object.salary_min }} {{ object.currency }}</p>
                            {% elif object.salary_max %}
                            <p>{{ object.salary_max }} {{ object.currency }}</p>
                            {% endif %}
                        </td>
                        <td scope="col" class="text-right">
                            <p><a href="{% url 'jobseeker:resume_detail' jobseeker.pk object.id %}">просмотреть резюме</a></p>
                            <p><a class="btn-resume-delete" href="{% url 'jobseeker:resume_delete' jobseeker.pk object.id %}">удалить резюме</a></p>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
                </tbody>
            </table>
                <a class="btn btn-primary mb-3" href="{% url 'jobseeker:resume' jobseeker.pk %}">
                    Создать резюме
                </a>
            <h1 class="my-5">Черновики резюме</h1>
            <table class="table employer_table">
                <tbody>
            {% if not drafts %}
                <tr>
                    <td scope="col"><p>У вас нет ни одного сохраненого черновика</p></td>
                </tr>
            {% else %}
                {% for object in drafts %}
                    <tr>
                        <td scope="col">
                            <p>{{ object.name }}</p>
                            {% if object.salary_min and object.salary_max %}
                            <p>{{ object.salary_min }} - {{ object.salary_max }} {{ object.currency }}</p>
                            {% elif object.salary_min %}
                            <p>{{ object.salary_min }} {{ object.currency }}</p>
                            {% elif object.salary_max %}
                            <p>{{ object.salary_max }} {{ object.currency }}</p>
                            {% endif %}
                        </td>
                        <td scope="col" class="text-right">
                            <p><a href="{% url 'jobseeker:resume_detail' jobseeker.pk object.id %}">просмотреть резюме</a></p>
                            <p><a class="btn-resume-delete" href="{% url 'jobseeker:resume_delete' jobseeker.pk object.id %}">удалить резюме</a></p>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
                </tbody>
            </table>
            <h1 class="my-5">Избранные вакасии ({{ favorites|length }})</h1>
                <a class="btn btn-outline-primary" role="button"
                   href="{% url 'jobseeker:favorite_list' object.pk %}">перейти в раздел</a>
            <h1 class="my-5">Отклики ({{ offers|length }})</h1>
                <a class="btn btn-outline-primary" role="button"
                   href="{% url 'jobseeker:offer_list' object.pk %}">перейти в раздел</a>
            <h1 class="my-5">Сообщения от модератора портала ({{ messages|length }})</h1>
            <a class="btn btn-outline-primary" role="button"
                   href="{% url 'jobseeker:messages' object.pk %}">перейти в раздел</a>
        </div>
        {% else %}
        <div class="col-12">
            <p class="text-center">Ваш профиль отправлен на постмодерацию модератору портала. После
                прохождения модерации вам будет доступна вся функциональность портала,  включая размещение
                резюме на портале, добавление вакансий в избранное, рассылка своих резюме
                работодателям. При одобрении модератором портала данных вашего профиля вам на вашу
                почту придет уведомление об успешной модерации. В случае отказа в прохождении
                модерации вам также будет направлено письмо с причинмами отказа. В случае отказа
                вы можете снова отредактировать свой профиль с учетом замечаний.
            </p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

jobseekerapp/templates/jobseekerapp/offer_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <p class="h4 font-weight-bold mt-4">Мои отклики</p>
            {% if object_list %}
                {% for object in object_list %}
                {% if object.direction == 'I' %}
                <hr>
                <p class="text-muted mb-3">{{ object.get_direction_display }} </p>
                <p class="h6 mb-1"><b><a href="{% url 'employer:vacancy_view' object.vacancy.employer.pk object.vacancy.pk %}">{{ object.vacancy.employer.company_name }} ({{ object.vacancy.vacancy_name }})</a></b></p>
                <p class="h6 mb-1">{{ object.date|date:'d.m.Y' }} </p>
                <p class="h6 mb-1">резюме: <a href="{% url 'jobseeker:resume_detail' jobseeker.pk object.id %}"> {{ object.resume.name }} </a></p>
                <p class="text-muted mb-0">{{ object.vacancy.get_status_display }} </p>
                {% if object.cover_letter %}<p class="mb-0">{{ object.cover_letter|linebreaks|truncatewords:40 }} Контактное лицо: {{ object.vacancy.contact_person }}</p>
                {% else %}
                <p class="mb-0">Нас заинтерсовало ваше резюме. Направляем вам предложение по нашей вакансии. В случае ответной
                заинтересованности просим с нами связаться. Контактное лицо: {{ object.vacancy.contact_person }}.</p>{% endif %}
                {% if object.contact_phone %}
                <p class="mb-0">Контактный телефон: {{ object.contact_phone|phone_number }}</p>
                {% endif %}
                <a href="{% url 'employer:vacancy_view' object.vacancy.employer.pk object.vacancy.pk %}">Просмотреть предложенную вакансию.</a>
            {% else %}
                <hr>
                <p class="text-muted mb-3">{{ object.get_direction_display }} </p>
                <p class="h6 mb-1"><b><a href="{% url 'employer:vacancy_view' object.vacancy.employer.pk object.vacancy.pk %}">{{ object.vacancy.employer.company_name }} ({{ object.vacancy.vacancy_name }})</a></b></p>
                <p class="h6 mb-1">{{ object.date|date:'d.m.Y' }} </p>
                <p class="h6 mb-1">резюме: <a href="{% url 'jobseeker:resume_detail' jobseeker.pk object.id %}"> {{ object.resume.name }} </a></p>
                <p class="text-muted mb-3">{{ object.get_status_display }} </p>
                {% if object.contact_phone %}
                <p class="mb-0">Контактный телефон:
                    {{ object.contact_phone|phone_number }}</p>
                {% endif %}
                <p class="mb-1">{{ object.cover_letter|linebreaks|truncatewords:40 }}</p>
            {% endif %}
            {% endfor %}
            {% else %}
            <hr>
             <p class="pt-0">Откликов ещё нет</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

jobseekerapp/templates/jobseekerapp/resume_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
   <div class="container">
       <h3 class="my-3 text-center">Уверены, что хотите удалить ваше резюме {{ object.name }}?</h3>
       <form action="{% url 'jobseeker:resume_delete' user.pk object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger form-control last" type="submit" value="удалить">
       </form>
       <a class="btn btn-round form-control last" href="{% url 'jobseeker:cabinet' user.pk %}">отмена</a>
   </div>
{% endblock %}

jobseekerapp/templates/jobseekerapp/resume_education_create.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
   <div class="container">
       <h3 class="my-4 text-center"> Информация об образовании </h3>
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
       </form>
       <button class="btn btn-round form-control last">
            <a href="{% url 'jobseeker:resume_detail' user.pk resume.id %}">
                к резюме
            </a>
        </button>
   </div>

{% endblock %}