authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/employer/', authapp.register_employer, name='register_employer'),
    path('register/jobseeker/', authapp.register_jobseeker, name='register_jobseeker'),
    path('edit/', authapp.edit, name='edit'),
    path('jobseeker/<int:pk>/edit/', authapp.JobseekerUpdateView.as_view(), name='edit_jobseeker'),
    path('edit/password/', authapp.UpdatePasswordView.as_view(), name='edit_password'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    re_path(r'^seeker_verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.seeker_verify, name='seeker_verify'),
    path('email_verify/', authapp.email_verify, name='email_verify'),
    path('edit/employer_password/', authapp.employer_change_password,
         name='employer_change_password')
]

employerapp/urls.py
from django.urls import path

from employerapp import views

app_name = 'employerapp'

urlpatterns = [
    path('<int:emp_id>/', views.employer_cabinet, name='main_cabinet'),
    path('<int:emp_id>/drafts/', views.vacancy_draft, name='drafts'),
    path('<int:emp_id>/published/', views.vacancy_published, name='published'),
    path('<int:emp_id>/messages/', views.messages, name='messages'),
    path('<int:emp_id>/hide/', views.vacancy_hide, name='hide'),
    path('<int:emp_id>/responses/', views.responses, name='responses'),
    path('<int:emp_id>/my_offers/', views.my_offers, name="my_offers"),
    path('<int:emp_id>/vacancy_create/', views.vacancy_create, name='vacancy_create'),
    path('<int:emp_id>/vacancy_draft_edit/<int:pk>/', views.vacancy_edit_draft,
         name='vacancy_edit_draft'),
    path('<int:emp_id>/vacancy_edit/<int:pk>/', views.vacancy_edit, name='vacancy_edit'),
    path('<int:emp_id>/vacancy_delete/<int:pk>/', views.vacancy_delete, name='vacancy_delete'),
    path('<int:emp_id>/vacancy_view/<int:pk>/', views.vacancy_view, name='vacancy_view'),
    path('<int:emp_id>/send_offer/<int:pk>', views.send_offer, name='send_offer'),
    path('<int:emp_id>/favorites/', views.favorites, name='favorites'),
    path('<int:emp_id>/favorite/create/', views.add_favorite, name='create_favorite'),
    path('<int:emp_id>/favorite_<int:pk>/delete/', views.delete_favorite, name='delete_favorite'),
    path('<int:emp_id>/search_resume/', views.search_resume, name='search_resume')
]

jobseekerapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from jobseekerapp import views

app_name = 'jobseekerapp'

urlpatterns = [
    path('<int:jobseeker_id>/', views.JobseekerDetailView.as_view(), name='cabinet'),
    path('<int:jobseeker_id>/resume/', views.create_resume, name='resume'),
    path('<int:seeker_id>/messages', views.messages, name='messages'),
    path('<int:jobseeker_id>/resume/<int:pk>/', login_required(views.ResumeDetailView.as_view()), name='resume_detail'),
    path('resume/<int:pk>/external/', views.ResumeExternalDetailView.as_view(), name='resume_external_detail'),
    path('<int:jobseeker_id>/resume/<int:pk>/edit/', views.resume_update, name='resume_update'),
    path('<int:jobseeker_id>/resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(), name='resume_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/', views.ResumeExperienceCreateView.as_view(),
         name='resume_experience'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/edit/',
         views.ResumeExperienceUpdateView.as_view(), name='resume_experience_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/delete/',
         views.ResumeExperienceDeleteView.as_view(), name='resume_experience_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/',
         views.ResumeEducationCreateView.as_view(), name='resume_education'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/edit/',
         views.ResumeEducationUpdateView.as_view(), name='resume_education_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/delete/',
         views.ResumeEducationDeleteView.as_view(), name='resume_education_delete'),
    path('<int:jobseeker_id>/offer/<int:vacancy_id>/create/', views.JobseekerOfferCreateView.as_view(),
         name='offer_create'),
    # path('<int:jobseeker_id>/offer/', views.JobseekerOfferListView.as_view(), name='offer_list'),
    path('<int:jobseeker_id>/offer/', views.offer_list, name='offer_list'),
    path('<int:jobseeker_id>/favorite/', views.JobseekerFavoriteListView.as_view(), name='favorite_list'),
    path('<int:jobseeker_id>/favorite/<int:pk>/delete/', views.JobseekerFavoriteDeleteView.as_view(),
         name='favorite_delete'),
    path('<int:jobseeker_id>/favorite/create/', views.add_favorite, name='favorite_create'),
    path('<int:jobseeker_id>/search_vacancy/',
         views.SearchVacancyListView.as_view(), name='search_vacancy'),
]

recruitsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views
from recruitsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('<int:page>/', views.main, name='main'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('site_news/<int:page>/', views.news, name='news'),
    path('news/search_news/', views.search_news, name='search_news'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('employer/', include('employerapp.urls', namespace='employer')),
    path('jobseeker/', include('jobseekerapp.urls', namespace='jobseeker')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.db import models


class IndustryType(models.Model):
    descx = models.CharField(verbose_name='Описание типа отрасли', max_length=64)

    class Meta:
        verbose_name_plural = 'Типы отраслей'

    def __str__(self):
        return self.descx


class Employer(models.Model):
    DRAFT = 'draft'
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    EMPLOYER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором'),
        (DRAFT, 'черновик')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    company_name = models.CharField(verbose_name='название компании', max_length=256, unique=True)
    tax_number = models.CharField(verbose_name='ИНН компании', max_length=16, blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11, blank=True)
    site = models.CharField(verbose_name='сайт компании', max_length=32, blank=True)
    industry_type = models.ForeignKey(IndustryType, on_delete=models.CASCADE, null=True, blank=True)
    short_description = models.TextField(verbose_name='краткое описание компании', blank=True)
    logo = models.ImageField(upload_to='company_logo', blank=True)
    city = models.CharField(verbose_name='город расположения компании', max_length=64, blank=True)
    is_active = models.BooleanField(default=True)
    status = models.CharField(verbose_name='статус компании на сайте',
                              choices=EMPLOYER_STATUS_CHOICES, default=NEED_MODER,
                              max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                        'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Работодатели'

    def __str__(self):
        return self.company_name


class Jobseeker(models.Model):
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    JOBSEEKER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором')
    )
    GENDER_CHOICES = (
        ('m', 'мужской'),
        ('f', 'женский'),
    )
    MARRIED_STATUS_CHOICES = (
        ('h', 'холост'),
        ('m', 'замужем/женат'),
        ('d', 'разведен/разведена'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    middle_name = models.CharField(verbose_name='отчество', max_length=32)
    gender = models.CharField(verbose_name='пол', max_length=16, choices=GENDER_CHOICES)
    birthday = models.DateField(verbose_name='дата рождения', null=True, blank=True)
    city = models.CharField(verbose_name='город', max_length=64)
    married_status = models.CharField(verbose_name='Статус в браке', max_length=1, choices=MARRIED_STATUS_CHOICES)
    photo = models.ImageField(upload_to='jobseeker_photo', blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11)
    about = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    status = models.CharField(verbose_name='статус соискателя на сайте',
                choices=JOBSEEKER_STATUS_CHOICES, default=NEED_MODER, max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                                            'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Соискатели'

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} (статус: {self.status})'

employerapp/models.py
from datetime import datetime

from django.db import models

from authapp.models import Employer


class Vacancy(models.Model):
    RUB = 'RUB'
    USD = 'USD'
    EUR = 'EUR'
    CURRENCY_CHOICE = (
        (RUB, 'RUB'),
        (USD, 'USD'),
        (EUR, 'EUR')
    )
    FULL = 'полная занятость'
    PART = 'частичная занятость'
    PRJ = 'занятость по проекту'
    REM = 'удаленная работа'
    TYPE_VACANCY = (
        (FULL, 'полная занятость'),
        (PART, 'частичная занятость'),
        (PRJ, 'занятость по проекту'),
        (REM, 'удаленная работа')
    )
    vacancy_name = models.CharField(verbose_name='название вакансии', max_length=128)
    city = models.CharField(verbose_name='город', max_length=64)
    vacancy_type = models.CharField(verbose_name='тип занятости', max_length=32,
                                    choices=TYPE_VACANCY, default=FULL)
    min_salary = models.CharField(verbose_name='минимальный уровень з/п', max_length=32, blank=True,
                              help_text='поле необязательное для заполнения')
    max_salary = models.CharField(verbose_name='максимальный уровень з/п', max_length=32,
                                  blank=True, help_text='поле необязательное для заполнения')
    currency = models.CharField(verbose_name='валюта', max_length=4, blank=True,
                                choices=CURRENCY_CHOICE, help_text='поле необязательное для '
                                                                   'заполнения')
    description = models.TextField(verbose_name='описание / обязанности', max_length=1024)
    requirements = models.TextField(verbose_name='требования к кандидату', max_length=1024)
    conditions = models.TextField(verbose_name='что мы предлагаем', max_length=1024, blank=True,
                                  help_text='поле необязательное для заполнения')
    published = models.DateField(verbose_name='дата публикации', default=datetime.now)
    contact_person = models.CharField(verbose_name='контактное лицо', max_length=128)
    contact_email = models.EmailField(verbose_name='контактная почта', blank=True,
                                      help_text='поле необязательное')
    hide = models.BooleanField(verbose_name='вакансия удалена / скрыта', default=False)
    action = models.CharField(verbose_name='статус вакансии', max_length=64, choices=Employer.EMPLOYER_STATUS_CHOICES)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    failed_moderation = models.TextField(verbose_name='Сообщение в случае непрохождения '
                                            'модерации вакансии', max_length=254, blank=True)

    def __str__(self):
        return f'{self.vacancy_name} ({self.employer.company_name})'

    class Meta:
        verbose_name_plural = 'Вакансии'

    def save(self, *args, **kwargs):
        if self.action == 'moderation_ok' or self.action == 'moderation_reject':
            self.published = datetime.now()
        super(Vacancy, self).save(*args, **kwargs)

    def get_favorite_id(self, user_id):
        favorite = self.favoritevacancies.select_related().filter(user=user_id)
        if favorite:
            return favorite.first().id
        return None


class SendOffers(models.Model):
    NEW = 'new'
    READ = 'read'
    OFFER_STATUS = (
        (NEW, 'новое (не прочитано)'),
        (READ, 'прочитано'),
    )
    date = models.DateField(verbose_name='дата направления предложения', default=datetime.now)
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, verbose_name='выберите '
                            'вакансию по которой хотите направить предложение соискателю')
    resume = models.ForeignKey('jobseekerapp.Resume', on_delete=models.CASCADE, verbose_name='предложение для '
                                                                              'резюме')
    cover_letter = models.TextField(verbose_name='Сопроводительное письмо по предлагаемой '
                'вакансии', blank=True, max_length=524, help_text='поле не обязательное')
    contact_phone = models.CharField(max_length=12, blank=True, help_text='поле не обязательное',
                                     verbose_name='конт. тел с кем связываться по вакансии')
    status = models.CharField(verbose_name='статус предложения', max_length=32,
                              choices=OFFER_STATUS, default=NEW)

    class Meta:
        verbose_name_plural = 'Предложения для соискателей'

    def __str__(self):
        return f'{self.vacancy.employer.company_name} ({self.resume.name})'


class Favorites(models.Model):
    date = models.DateField(verbose_name='дата добавления в избранное', default=datetime.now)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    resume = models.ForeignKey('jobseekerapp.Resume', on_delete=models.CASCADE, verbose_name='избранное резюме',
                               related_name='favoriteresumes')

    class Meta:
        verbose_name_plural = 'Избранные резюме'

    def __str__(self):
        return f'{self.employer.company_name} ({self.resume.name})'

employerapp/templates/employerapp/delete_favorite.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="container my-5">
        Уверены, что хотите удалить из избранного резюме <strong>{{ favorite.resume.name }}</strong>?
        <div class="row mt-3 mb-5">
            <div class="col col-sm-6 d-flex">
                <form action="{% url 'employer:delete_favorite' employer.pk favorite.pk %}"
                      method="post">
                    {% csrf_token %}
                    <input class="btn btn-outline-danger mr-5" type="submit" value="удалить">
                </form>
                <a class="btn btn-outline-success" role="button"
                   href="{% url 'employer:favorites' employer.pk %}">отмена</a>
            </div>
        </div>
    </div>
{% endblock %}

employerapp/templates/employerapp/employer_cabinet.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<div class="container my-5">
    <h3 class="font-italic mb-5 text-center">Личный кабинет: {{ employer.company_name }} </h3>
    <div class="row">
        {% if employer.status == 'moderation_ok' %}
        <div class="col-5 col-sm-4 col-md-3 pr-sm-4">
            {% include 'employerapp/include/left-menu.html' %}
        </div>
        <div class="col-7 col-sm-8 col-md-9 pl-sm-5">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Поле</th>
                    <th scope="col">Данные</th>
                </tr>
                <tr>
                    <th scope="col">Деятельность</th>
                    <th scope="col">{{ industry_type }}</th>
                </tr>
                <tr>
                    <th scope="col">Телeфон</th>
                    <th scope="col">{{ employer.phone_number }}</th>
                </tr>
                <tr>
                    <th scope="col">Город</th>
                    <th scope="col">{{ employer.city }}</th>
                </tr>
                <tr>
                    <th scope="col">Сайт</th>
                    <th scope="col">{{ employer.site }}</th>
                </tr>
                <tr>
                    <th scope="col">Статус</th>
                    <th scope="col">{{ employer.get_status_display }}</th>
                </tr>
                </thead>
            </table>
            <div class="d-flex">
                <a class="my-4 px-3 btn btn-outline-primary" role="button" href="{% url 'auth:edit' %}">редактировать
                    профиль</a>
                <a class="btn btn-outline-success my-4 ml-4 px-3" role="button"
                   href="{% url 'auth:employer_change_password' %}">сменить пароль</a>
            </div>
        </div>
        {% else %}
        <div class="col-12">
            <p class="text-center">Ваш профиль отправлен на постмодерацию модератору портала. После
                прохождения модерации вам будет доступна вся функциональность портала,  включая размещение
                вакансий на портале, добавление резюме в избранное, направление предложений
                соискателям. При одобрении модератором портала данных вашего профиля вам на вашу
                почту придет уведомление об успешной модерации. В случае отказа в прохождении
                модерации вам также будет направлено письмо с причинмами отказа. В случае отказа
                вы можете снова отредактировать свой профиль с учетом замечаний.
            </p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

employerapp/templates/employerapp/employer_responses.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h3 class="font-italic mb-5 text-center">Личный кабинет: {{ employer.company_name }} </h3>
    <div class="row justify-content-around">
        <div class="col-5 col-sm-4 col-md-3 mb-5">
            {% include 'employerapp/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-md-9">
            <h5 class="font-italic mb-3">Отклики по вакансиям:</h5>
            {% if responses %}
            {% for item in responses %}
            <span class="font-weight-bold mb-0">{{ item.date|date:"d.m.Y" }}</span> Тема:
                отклик по вакансии <a href="{% url 'employer:vacancy_view' employer.pk item.vacancy.pk %}"> {{ item.vacancy.vacancy_name }}</a></span>
            <p class="mb-0">статус: <span class="{% if item.status == 'new' %}font-weight-bold{% endif %}">{{ item.get_status_display }}</span></p>
            <p class="mb-0">Текст отклика:</p>
            {% if item.cover_letter %}<p class="mb-5">{{ item.cover_letter }}<br>
            Прошу рассмотреть <a href="{% url 'jobseeker:resume_external_detail' item.resume.pk %}">мое
                резюме (желаемая должность: {{ item.resume.name }}).</a></p>{% else %}
            <p class="mb-5">Меня очень заинтересовала ваша вакансия. Прошу рассмотреть <a
                href="{% url 'jobseeker:resume_external_detail' item.resume.pk %}">мое
                резюме (желаемая должность: {{ item.resume.name }}).</a></p>
            {% endif %}
            {% endfor %}
            {% else %}
            <p>У вас нет ни одного отклика на вакансию</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

employerapp/templates/employerapp/favorites.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h3 class="font-italic mb-5 text-center">Личный кабинет: {{ employer.company_name }} </h3>
    <div class="row justify-content-around">
        <div class="col-5 col-sm-4 col-md-3 pr-4 mb-5">
            {% include 'employerapp/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-md-9">
            {% if favorites %}
            <h5 class="mb-4 font-italic">Избранные резюме:</h5>
            {% for item in favorites %}
            <p class="font-italic small font-weight-bold">Добавлено в избранное: {{ item.date|date:'d.m.Y.' }}</p>
            <div class="d-flex">
                <h4 style="color: blue;"><a href="{% url 'jobseeker:resume_external_detail' item.resume.pk %}">{{ item.resume.user.user.last_name }} {{ item.resume.user.user.first_name }}
                    {{ item.resume.user.middle_name }}</a></h4>
                <p class="h5 ml-5" style="color:black;">Уровень з/п:
                    {% if item.resume.salary_min and item.resume.salary_max %}{{ item.resume.salary_min }} - {{ item.resume.salary_max }} {{ item.resume.currency }}
                    {% elif item.resume.salary_min %} от {{ item.resume.salary_min }} {{ item.resume.currency }}
                    {% elif item.resume.salary_max %} до {{ item.resume.salary_max }} {{ item.resume.currency }}
                    {% else %} не указана
                    {% endif %}
                </p>
            </div>
            <p class="small text-muted mb-0">{{ item.resume.user.city }}</p>
            <p class="text-muted mb-3">Дата рождения:
                {{item.resume.user.birthday|date:"d.m.Y"}}
            <span class="mb-3 ml-5">Семейный статус:
                {{item.resume.user.get_married_status_display}}</span></p>
            <p>Желаемая должность: {{ item.resume.name }}</p>
            <div class="d-flex">
                <strong>Навыки:</strong> <span class="ml-3">{{item.resume.key_skills|linebreaks|truncatewords:20}}</span>
            </div>
            <p>Дата публикации: {{item.resume.updated_at|date:"d.m.Y" }}</p>
            <div class="d-flex mb-5">
                <a class="btn btn-outline-primary" role="button"
                   href="{% url 'employer:delete_favorite' employer.pk item.pk %}">
                    Удалить из избранного</a>
                <a class="btn btn-outline-primary px-4 ml-5" role="button"
                   href="{% url 'employer:send_offer' user.pk item.resume.pk %}">Направить
                    предложение
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p class="text-center">У вас еще нет ни одного избранного резюме.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

employerapp/templates/employerapp/search_resume.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h3 class="font-italic text-center mb-5">Результаты поиска</h3>
    <div class="row justify-content-center">
        <div class="col-12 col-sm-11">
            {% if object_list %}
            <p class="mb-3"><a class="h5" href="{% url 'main' 1 %}">&laquo вернуться к поиску</a></p>
            {% for object in object_list %}
            <div class="mb-5">
                <div class="d-flex align-items-center">
                    <h4 style="color: blue;"><a
                            href="{% url 'jobseeker:resume_external_detail' object.id %}">{{ object.user.last_name }} {{ object.user.first_name }}
                        {{ object.user.jobseeker.middle_name }}</a></h4>
                    <p class="ml-5">
                        <form action="{% url 'main' 1 %}" method="post" class="favorite">{% csrf_token %}
                            <input type="hidden" name="checked" value="{{ object.pk }}">
                            <button class="btn btn-clear add-favorite" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                            </svg></button>
                        </form>
                    </p>
                    <p class="h5 ml-5" style="color:black;">Уровень з/п:
                        {% if object.salary_min and object.salary_max %}{{ object.salary_min }} -
                        {{ object.salary_max }} {{ object.currency }}
                        {% elif object.salary_min %} от {{ object.salary_min }} {{ object.currency }}
                        {% elif object.salary_max %} до {{ object.salary_max }} {{ object.currency }}
                        {% else %} не указана
                        {% endif %}
                    </p>
                </div>
                <p class="small text-muted mb-0">{{ object.user.jobseeker.city }}</p>
                <div class="d-flex pl-0 col-12 col-sm-7 justify-content-between mb-0">
                    <p class="text-muted mb-0">Дата рождения:
                    {{object.user.jobseeker.birthday|date:"d.m.Y"}}</p>
                    <p class="text-muted mb-0">Семейный статус:
                    {{object.user.jobseeker.get_married_status_display}}</p>
                </div>
                <div class="d-flex pl-0 col-12 col-sm-7 justify-content-between">
                    <p class="text-muted">тел: {{ object.user.jobseeker.phone_number }}</p>
                    <p class="text-muted">email: {{ object.user.email }}</p>
                </div>
                <p><span class="font-weight-bold">Желаемая должность:</span> {{ object.name }}</p>
                <div class="d-flex">
                    <strong>Навыки:</strong> <span class="ml-3">{{ object.key_skills|linebreaks|truncatewords:20}}</span>
                </div>
                <p>Дата публикации: {{object.updated_at|date:"d.m.Y" }}</p>
                <div class="d-flex">
                    <a class="btn btn-outline-primary" role="button"
                       href="{% url 'jobseeker:resume_external_detail' object.pk %}">Просмотреть
                        резюме</a>
                    <a class="btn btn-outline-primary ml-5" role="button"
                       href="{% url 'employer:send_offer' user.pk object.pk %}">Направить
                        предложение</a>
                </div>
            </div>
            {% endfor %}

            <div class="text-center mt-4 mb-5">
            {% if object_list.has_previous %}
                <span>
                    <a class="h4"
                       href="?search=&city=&salary=&from=&till={{ search }}&page={{ object_list.previous_page_number }}">&laquo
                    </a>
                </span>
            {% endif %}
                <span class="px-3 font-italic font-weight-bold">страница {{ object_list.number }}
                    из {{ object_list.paginator.num_pages }}</span>
            {% if object_list.has_next %}
                <span>
                    <a class="h4" href="?search=&city=&salary=&from=&till={{ search }}&page={{ object_list.next_page_number }}">
                        &raquo</a>
                </span>
            {%endif%}
            </div>
            {% else %}
            <p>Поиск не дал результатов. Попробуйте изменить поиск.</p>
            <a href="{% url 'main' 1 %}">вернуться к поиску</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}