authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/employer/', authapp.register_employer, name='register_employer'),
    path('register/jobseeker/', authapp.register_jobseeker, name='register_jobseeker'),
    path('edit/', authapp.edit, name='edit'),
    path('jobseeker/<int:pk>/edit/', authapp.JobseekerUpdateView.as_view(), name='edit_jobseeker'),
    path('edit/password/', authapp.UpdatePasswordView.as_view(), name='edit_password'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    re_path(r'^seeker_verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.seeker_verify, name='seeker_verify'),
    path('email_verify/', authapp.email_verify, name='email_verify'),
    path('edit/employer_password/', authapp.employer_change_password,
         name='employer_change_password')
]

employerapp/urls.py
from django.urls import path

from employerapp import views

app_name = 'employerapp'

urlpatterns = [
    path('<int:emp_id>/', views.employer_cabinet, name='main_cabinet'),
    path('<int:emp_id>/drafts/', views.vacancy_draft, name='drafts'),
    path('<int:emp_id>/published/', views.vacancy_published, name='published'),
    path('<int:emp_id>/messages/', views.messages, name='messages'),
    path('<int:emp_id>/hide/', views.vacancy_hide, name='hide'),
    path('<int:emp_id>/responses/', views.responses, name='responses'),
    path('<int:emp_id>/my_offers/', views.my_offers, name="my_offers"),
    path('<int:emp_id>/vacancy_create/', views.vacancy_create, name='vacancy_create'),
    path('<int:emp_id>/vacancy_draft_edit/<int:pk>/', views.vacancy_edit_draft,
         name='vacancy_edit_draft'),
    path('<int:emp_id>/vacancy_edit/<int:pk>/', views.vacancy_edit, name='vacancy_edit'),
    path('<int:emp_id>/vacancy_delete/<int:pk>/', views.vacancy_delete, name='vacancy_delete'),
    path('<int:emp_id>/vacancy_view/<int:pk>/', views.vacancy_view, name='vacancy_view'),
    path('<int:emp_id>/send_offer/<int:pk>', views.send_offer, name='send_offer'),
    path('<int:emp_id>/favorites/', views.favorites, name='favorites'),
    path('<int:emp_id>/favorite/create/', views.add_favorite, name='create_favorite'),
    path('<int:emp_id>/favorite_<int:pk>/delete/', views.delete_favorite, name='delete_favorite'),
    path('<int:emp_id>/search_resume/', views.search_resume, name='search_resume')
]

jobseekerapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from jobseekerapp import views

app_name = 'jobseekerapp'

urlpatterns = [
    path('<int:jobseeker_id>/', views.JobseekerDetailView.as_view(), name='cabinet'),
    path('<int:jobseeker_id>/resume/', views.create_resume, name='resume'),
    path('<int:seeker_id>/messages', views.messages, name='messages'),
    path('<int:jobseeker_id>/resume/<int:pk>/', login_required(views.ResumeDetailView.as_view()), name='resume_detail'),
    path('resume/<int:pk>/external/', views.ResumeExternalDetailView.as_view(), name='resume_external_detail'),
    path('<int:jobseeker_id>/resume/<int:pk>/edit/', views.resume_update, name='resume_update'),
    path('<int:jobseeker_id>/resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(), name='resume_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/', views.ResumeExperienceCreateView.as_view(),
         name='resume_experience'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/edit/',
         views.ResumeExperienceUpdateView.as_view(), name='resume_experience_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/experience/<int:pk>/delete/',
         views.ResumeExperienceDeleteView.as_view(), name='resume_experience_delete'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/',
         views.ResumeEducationCreateView.as_view(), name='resume_education'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/edit/',
         views.ResumeEducationUpdateView.as_view(), name='resume_education_update'),
    path('<int:jobseeker_id>/resume/<int:resume_id>/education/<int:pk>/delete/',
         views.ResumeEducationDeleteView.as_view(), name='resume_education_delete'),
    path('<int:jobseeker_id>/offer/<int:vacancy_id>/create/', views.JobseekerOfferCreateView.as_view(),
         name='offer_create'),
    # path('<int:jobseeker_id>/offer/', views.JobseekerOfferListView.as_view(), name='offer_list'),
    path('<int:jobseeker_id>/offer/', views.offer_list, name='offer_list'),
    path('<int:jobseeker_id>/favorite/', views.JobseekerFavoriteListView.as_view(), name='favorite_list'),
    path('<int:jobseeker_id>/favorite/<int:pk>/delete/', views.JobseekerFavoriteDeleteView.as_view(),
         name='favorite_delete'),
    path('<int:jobseeker_id>/favorite/create/', views.add_favorite, name='favorite_create'),
    path('<int:jobseeker_id>/search_vacancy/',
         views.SearchVacancyListView.as_view(), name='search_vacancy'),
]

recruitsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp import views
from recruitsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('<int:page>/', views.main, name='main'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('site_news/<int:page>/', views.news, name='news'),
    path('news/search_news/', views.search_news, name='search_news'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('employer/', include('employerapp.urls', namespace='employer')),
    path('jobseeker/', include('jobseekerapp.urls', namespace='jobseeker')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.db import models


class IndustryType(models.Model):
    descx = models.CharField(verbose_name='Описание типа отрасли', max_length=64)

    class Meta:
        verbose_name_plural = 'Типы отраслей'

    def __str__(self):
        return self.descx


class Employer(models.Model):
    DRAFT = 'draft'
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    EMPLOYER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором'),
        (DRAFT, 'черновик')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    company_name = models.CharField(verbose_name='название компании', max_length=256, unique=True)
    tax_number = models.CharField(verbose_name='ИНН компании', max_length=16, blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11, blank=True)
    site = models.CharField(verbose_name='сайт компании', max_length=32, blank=True)
    industry_type = models.ForeignKey(IndustryType, on_delete=models.CASCADE, null=True, blank=True)
    short_description = models.TextField(verbose_name='краткое описание компании', blank=True)
    logo = models.ImageField(upload_to='company_logo', blank=True)
    city = models.CharField(verbose_name='город расположения компании', max_length=64, blank=True)
    is_active = models.BooleanField(default=True)
    status = models.CharField(verbose_name='статус компании на сайте',
                              choices=EMPLOYER_STATUS_CHOICES, default=NEED_MODER,
                              max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                        'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Работодатели'

    def __str__(self):
        return self.company_name


class Jobseeker(models.Model):
    NEED_MODER = 'need_moderation'
    MODER_OK = 'moderation_ok'
    MODER_REJECT = 'moderation_reject'
    JOBSEEKER_STATUS_CHOICES = (
        (NEED_MODER, 'требуется модерация'),
        (MODER_OK, 'модерация пройдена успешно'),
        (MODER_REJECT, 'отклонено модератором')
    )
    GENDER_CHOICES = (
        ('m', 'мужской'),
        ('f', 'женский'),
    )
    MARRIED_STATUS_CHOICES = (
        ('h', 'холост'),
        ('m', 'замужем/женат'),
        ('d', 'разведен/разведена'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    middle_name = models.CharField(verbose_name='отчество', max_length=32)
    gender = models.CharField(verbose_name='пол', max_length=16, choices=GENDER_CHOICES)
    birthday = models.DateField(verbose_name='дата рождения', null=True, blank=True)
    city = models.CharField(verbose_name='город', max_length=64)
    married_status = models.CharField(verbose_name='Статус в браке', max_length=1, choices=MARRIED_STATUS_CHOICES)
    photo = models.ImageField(upload_to='jobseeker_photo', blank=True)
    phone_number = models.CharField(verbose_name='телефон', max_length=11)
    about = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    status = models.CharField(verbose_name='статус соискателя на сайте',
                choices=JOBSEEKER_STATUS_CHOICES, default=NEED_MODER, max_length=32)
    failed_moderation = models.CharField(max_length=512, blank=True, verbose_name='поле '
                                            'заполняется в случае отклонения модерации')
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(datetime.now() + timedelta(hours=24)))

    def is_activation_key_expired(self):
        if datetime.now() > self.activation_key_expires:
            return True
        else:
            return False

    class Meta:
        verbose_name_plural = 'Соискатели'

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} (статус: {self.status})'

mainapp/models.py
from datetime import datetime

from django.db import models


class News(models.Model):

    title = models.CharField(verbose_name="заголовок", max_length=128)
    published = models.DateField(verbose_name="опубликовано", default=datetime.now)
    description = models.TextField(verbose_name="текст новости")
    is_active = models.BooleanField(verbose_name='новость активна', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Новости'

mainapp/views.py
from itertools import chain

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.models import Employer
from employerapp.models import Vacancy, Favorites
from django.contrib.auth.decorators import login_required

from authapp.models import Employer
from employerapp.models import Vacancy
import jobseekerapp.models as jobseek_model
from mainapp.models import News


def main(request, page=None):
    title = 'Главная'
    if page is None:
        page = 1
        return HttpResponseRedirect(reverse('main', kwargs={'page': page}))
    news = News.objects.filter(is_active=True).order_by('-published')
    employers = Employer.objects.filter(is_active=True, status=Employer.MODER_OK).order_by('?')[:6]
    vacancies = Vacancy.objects.filter(action='moderation_ok')
    if vacancies:
        for vacancy in vacancies:
            is_favorite = jobseek_model.Favorite.objects.filter(user=request.user.id,
                                                                vacancy=vacancy.id).first()
            setattr(vacancy, "is_favorite", True if is_favorite else False)
    resume_all = jobseek_model.Resume.objects.all().filter(status='opened').order_by('updated_at')
    if resume_all and request.user.is_authenticated and getattr(request.user, 'employer', None):
        for resume in resume_all:
            is_favorite = Favorites.objects.filter(employer=request.user.employer,
                                                   resume=resume.id).first()
            setattr(resume, "is_favorite", True if is_favorite else False)
    paginator = Paginator(news, 4)
    try:
        news_paginator = paginator.page(page)
    except PageNotAnInteger:
        news_paginator = paginator.page(1)
    except EmptyPage:
        news_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'news': news_paginator,
        'employers': employers,
        'vacancies': vacancies,
        'resume_all': resume_all
    }
    return render(request, 'mainapp/index.html', context)


def news_detail(request, pk):
    one_news = News.objects.get(pk=pk)
    title = one_news.pk
    url = f'http://pavelusov79.pythonanywhere.com{request.path}'
    context = {
        'title': title,
        'one_news': one_news,
        'url': url
    }
    return render(request, 'mainapp/news_detail.html', context)


def search_news(request):
    title = 'Поиск новостей'
    search = request.GET.get('search')
    search_paginator = None
    if search:
        query = []
        results = News.objects.filter(Q(title__icontains=search) | Q(description__icontains=search),
                                      is_active=True).order_by(
            '-published')
        query.append(results)
        query = list(chain(*query))

        page = request.GET.get('page')
        paginator = Paginator(query, 3)
        try:
            search_paginator = paginator.page(page)
        except PageNotAnInteger:
            search_paginator = paginator.page(1)
        except EmptyPage:
            search_paginator = paginator.page(paginator.num_pages)

    context = {'title': title, 'search_news': search_paginator, 'search': search}

    return render(request, 'mainapp/search_news.html', context)


def news(request, page=1):
    title = 'Новости'
    news = News.objects.filter(is_active=True).order_by('-published')
    paginator = Paginator(news, 4)
    try:
        news_paginator = paginator.page(page)
    except PageNotAnInteger:
        news_paginator = paginator.page(1)
    except EmptyPage:
        news_paginator = paginator.page(paginator.num_pages)

    context = {'title': title, 'news': news_paginator}

    return render(request, 'mainapp/news.html', context)

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
{% if user.is_authenticated and user.employer %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <p class="h4 font-italic">Добро пожаловать {{user.employer.company_name}} на портал IT
                Portal!</p>
            <p class="mb-5">Статус: Работодатель</p>
            <form action="{% url 'employerapp:search_resume' user.employer.pk %}"
                  class="mb-5 search-form" method="get">
                <div class="form-group">
                    <label class="pl-0 col-2" for="search-field">Ключевые слова</label>
                    <input id="search-field" type="text" class="d-inline form-control col-8 col-sm-6 col-md-4"
                           name="search" placeholder="должность или навык...">
                    <span title="расширенный поиск"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                         height="16" fill="currentColor" class="bi bi-sliders" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
                    </svg></span>
                    <div class="extend my-3">
                        <label class="pl-0 col-2" for="city">Город</label>
                        <input class="mb-3 col-8 col-sm-6 col-md-4 form-control d-inline"
                               type="text" name="city" id="city"><br>
                        <!--<label class="pl-0 col-2" for="sex">Выберите пол</label>
                        <select name="sex" id="sex"
                                class="mb-3 col-8 col-sm-6 col-md-4 form-control d-inline">
                            <option value="none"></option>
                            <option value="m">мужской</option>
                            <option value="f">женский</option>
                        </select><br>-->
                        <div class="d-flex pl-0 col-10 col-sm-8 col-md-6">
                            <label class="mb-3 col-4 pl-0" for="salary">Уровень дохода от</label>
                            <input type="number" name="salary" id="salary"
                                   class="mb-3 ml-2 form-control d-inline col-5">
                            <select name="currency" id="" class="ml-3 col-3 form-control d-inline">
                                <option value="RUB">RUB</option>
                                <option value="EUR">EUR</option>
                                <option value="USD">USD</option>
                            </select>
                        </div>
                        <div class="d-flex pl-0 col-10 col-sm-8 col-md-6">
                            <span class="col-4 px-0 col-form-label">Объявления за период от
                            </span><input
                                class="ml-2 form-control d-inline px-1 col-5" type="date"
                                name="from_date" id="from_date">
                            <span class="px-3 col-form-label">до</span><input
                                class="form-control d-inline px-1 col-5" type="date" name="till_date" id="till_date">
                        </div>
                    </div>
                    <button class="btn btn-primary px-4 button-search" type="submit">поиск
                    </button>
                </div>
            </form>
            {% for resume in resume_all %}
            <div class="mb-5">
                <div class="d-flex align-items-center">
                    <h4 style="color: blue;"><a
                            href="{% url 'jobseeker:resume_external_detail' resume.id %}">{{ resume.user.user.last_name }} {{ resume.user.user.first_name }}
                        {{ resume.user.middle_name }}</a></h4>
                    <!--<p class="ml-5">
                        <form action="{% url 'main' 1 %}" method="post" class="favorite">{%
                        csrf_token %}-->
                    <p class="ml-5">
                    {% if not resume.is_favorite %}
                    <form action="{% url 'employer:create_favorite' user.employer.pk %}"
                              method="post" class="add-favorite">{% csrf_token %}
                        <input type="hidden" name="checked" value="{{ resume.pk }}">
                        <button class="btn btn-clear add-favorite" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                             fill="currentColor" class="bi bi-star" viewBox="0 0 16 16" style="fill:blue;">
                        <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                        </svg></button>
                    </form>
                    {% else %}
                    {% get_favorite_id_ resume user.id as favorite_id %}
                    <form action="{% url 'employer:delete_favorite' user.employer.pk favorite_id %}"
                              method="post" class="delete-favorite">{% csrf_token %}
                        <input type="hidden" name="checked" value="{{ resume.pk }}">
                        <button class="btn btn-clear delete-favorite" type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                             fill="currentColor" class="bi bi-star" viewBox="0 0 16 16" style="fill:blue;">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                        </svg></button>
                    </form>
                    {% endif %}
                    </p>
                    <p class="h5 ml-5" style="color:black;">Уровень з/п:
                        {% if resume.salary_min and resume.salary_max %}{{ resume.salary_min }} -
                        {{ resume.salary_max }} {{ resume.currency }}
                        {% elif resume.salary_min %} от {{ resume.salary_min }} {{ resume.currency }}
                        {% elif resume.salary_max %} до {{ resume.salary_max }} {{ resume.currency }}
                        {% else %} не указана
                        {% endif %}
                    </p>
                </div>
                <p class="small text-muted mb-0">{{ resume.user.city }}</p>
                <div class="d-flex pl-0 col-12 col-sm-7 justify-content-between mb-0">
                    <p class="text-muted mb-0">Дата рождения:
                    {{resume.user.birthday|date:"d.m.Y"}}</p>
                    <p class="text-muted mb-0">Семейный статус:
                    {{resume.user.get_married_status_display}}</p>
                </div>
                <div class="d-flex pl-0 col-12 col-sm-7 justify-content-between">
                    <p class="text-muted">тел: {{ resume.user.phone_number }}</p>
                    <p class="text-muted">email: {{ resume.user.user.email }}</p>
                </div>
                <p><span class="font-weight-bold">Желаемая должность:</span> {{ resume.name }}</p>
                <div class="d-flex">
                    <strong>Навыки:</strong> <span class="ml-3">{{resume.key_skills|linebreaks|truncatewords:20}}</span>
                </div>
                <div class="d-flex">
                    <p>Дата публикации: {{resume.updated_at|date:"d.m.Y" }}</p>
                    <a class="btn btn-outline-primary px-4 ml-5" role="button"
                       href="{% url 'employer:send_offer' user.pk resume.pk %}">Направить
                        предложение
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% elif user.is_authenticated and user.jobseeker %}
    {% include 'jobseekerapp/main.html' %}
{% else %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-8 col-md-9 about_h1">
            <h1 class="text-center font-italic mb-5">Новости IT Portal</h1>
            <form action="{% url 'search_news' %}" class="mb-5 search-form" method="get">
                <div class="form-group">
                    <input type="text" class="d-inline form-control col-8 col-sm-6 col-md-4"
                           name="search" placeholder="поиск новостей...">
                    <button id="search_news" class="btn btn-primary px-4" type="submit">поиск
                    </button>
                </div>
            </form>
            {% for item in news %}
            <div class="row mb-3 mt-5" id="{{ item.id }}">
                <div class="col-2 h5">{{ item.published|date:"d.m.y" }}</div>
                <div class="col-10 h5">{{ item.title|capfirst }}</div>
            </div>
            <div class="row mb-1">
                <div class="col mb-0 text_news">
                    {% if item.description|wordcount > 40 %}
                    {{ item.description|linebreaks|truncatewords:40 }}
                    {% else %} {{ item.description|linebreaks }}
                    {% endif %}
                    <p class="mb-2"><a href="{% url 'news_detail' item.pk%}"><small class="text-muted">
                        подробнее...</small></a></p>
                </div>
            </div>
            {% endfor %}
            <div class="text-center mb-2">
                {% if news.has_previous %}
                <span>
                    <a class="h4" href="{% url 'main' news.previous_page_number %}">&laquo</a>
                </span>
                {% endif %}
                <span class="px-3 font-italic font-weight-bold">страница {{ news.number }} из {{news.paginator.num_pages}}</span>
                {% if news.has_next %}
                <span>
                    <a class="h4" href="{% url 'main' news.next_page_number %}">&raquo</a>
                </span>
                {%endif%}
            </div>
        </div>
        <div class="col-8 col-sm-4 col-md-3 news_col">
            <h5 class="text-center mt-2 font-italic" style="color: #808000;">Вход для
                зарегистрированных пользователей</h5>
            <form class="w-100" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                <p class="mb-0 mt-2">Логин:</p>
                <input class="w-100" type="text" name="username">
                <p class="mb-0 mt-2">Пароль:</p>
                <input class="w-100" type="password" name="password">
                <br>
                <input class="btn btn-primary form-control mt-3 mb-3" type="submit"
                       value="войти на портал">
            </form>
            <p class="text-center text-muted mt-3 mb-2">регистрация:</p>
            <a class="btn btn-outline-primary w-100 mb-3" role="button" href="{% url 'auth:register_employer' %}">
                работодателя
            </a>
            <a class="btn btn-outline-primary w-100 mb-3" role="button" href="{% url 'auth:register_jobseeker' %}">
                соискателя
            </a>

        </div>
    </div>
    {% if employers %}
    <h3 class="text-center mt-5">Компании партнеры</h3>
    <div class="row justify-content-center mt-3">
        {% for item in employers %}
        <div class="col-6 col-sm-3 col-lg-2">
            <div class="card">
                {% if item.logo %}
                <img class="card-img-top" style="height:100px; width:cover;" src="/media/{{ item.logo }}" alt="Card image cap">
                {% else %}<p class="card-img-top pt-5 text-center font-weight-bold"
                             style="height:85px;">LOGO COMPANY</p>
                {% endif %}
                <div class="card-body">
                    <p class="card-text text-center font-italic" style="height: 3rem;">{{ item.company_name }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endif %}
{% endblock %}

mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <h1 class="font-italic text-center mb-5">Новости IT Portal</h1>
    <div class="row">
        <div class="col-12">
            <form action="{% url 'search_news' %}" class="mb-5" method="get">
                <div class="form-group">
                    <input type="text" class="d-inline form-control col-8 col-sm-6 col-md-4"
                           name="search" placeholder="поиск новостей...">
                    <button id="search_news" class="btn btn-primary px-4" type="submit">поиск
                    </button>
                </div>
            </form>
            {% for item in news %}
            <div class="row mb-3 mt-5" id="{{ item.id }}">
                <div class="col-2 h5">{{ item.published|date:"d.m.y" }}</div>
                <div class="col-10 h5">{{ item.title|capfirst }}</div>
            </div>
            <div class="row mb-1">
                <div class="col mb-0 text_news">
                    {% if item.description|wordcount > 40 %}
                    {{ item.description|linebreaks|truncatewords:40 }}
                    {% else %} {{ item.description|linebreaks }}
                    {% endif %}
                    <p class="mb-2"><a href="{% url 'news_detail' item.pk%}"><small class="text-muted">
                        подробнее...</small></a></p>
                </div>
            </div>
            {% endfor %}
            <div class="text-center mb-2">
                {% if news.has_previous %}
                <span>
                    <a class="h4" href="{% url 'news' news.previous_page_number %}">&laquo</a>
                </span>
                {% endif %}
                <span class="px-3 font-italic font-weight-bold">страница {{ news.number }} из {{news.paginator.num_pages}}</span>
                {% if news.has_next %}
                <span>
                    <a class="h4" href="{% url 'news' news.next_page_number %}">&raquo</a>
                </span>
                {%endif%}
            </div>
        </div>
    </div>
</div>
{% endblock %}